# Generated by Django 5.2.5 on 2025-08-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_task_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='progress',
            field=models.CharField(choices=[('NS', 'Not Started'), ('ST', 'Started'), ('CO', 'Completed'), ('FA', 'Failed')], default='NS', max_length=2),
        ),
    ]
